# Обзор глав {.unnumbered}

Здесь будет обзор. 

## Работа с табличными данными {.unnumbered}

* [@sec-TidyData] *Табличные данные*

* [@sec-base-table] *Манипуляции с табличными данными*

* [@sec-deep-table] *Расширенный анализ табличных данных*

## Визуализация данных {.unnumbered}

* [@sec-grammar-graphics] *Грамматика графики*

* [@sec-color] *Роль цвета для визуализации данных*

## Разведочный анализ данных {.unnumbered}

## Анализ объектов городской инфраструктуры {.unnumbered}

* [@sec-osm-base-map] *Создание картографических подложек на основе OpenStreetMap*

* [@sec-osm-graph-streets] *Графы дорожной сети*

* [@sec-osm-reachability] *Анализ степени достижимости географически распределенных объектов*

## Пространственный анализ данных {.unnumbered}

* [@sec-thermopoints] *Исследование термоточек в РФ*

* [@sec-rayshader] *3D-визуализация пространственных данных*

* [@sec-spatial-interactive] *Интерактивные карты*

## Основы машинного обучения {.unnumbered}

* [@sec-ML-basic-notions] *Основные понятия машинного обучения*

* [@sec-ML-tidy-principles] *Принципы машинного обучения на основе «аккуратных данных»*

* [@sec-ML-regression] *Регрессионный анализ* 

* [@sec-ML-cluster] *Кластерный анализ*

## Временные ряды {.unnumbered}

## Автоматизированные отчеты {.unnumbered}

## Приложения {.unnumbered}

