# проект
project:
  # тип проекта - веб-страница
  type: website

website:
  title: "Сайт"
  # панель навигации
  navbar:
    # цвет панели
    background: "#2860a1"
    # элементы панели
    left:
      # источник - файл
      - href: index.qmd
        # текст в панели навигации
        text: Исследование повторяемости ветров

format:
  html:
    # тема сайта
    theme: pulse
    # стиль CSS
    css: styles.css
    # содержание страницы
    toc: true

execute:
  # повторный рендеринг выполняется только при изменении исходного кода
  freeze: auto

